#
server:
  port: 8099
#
#?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ziheng_attendanceSystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: aa1234
#  mvc:
#    view:
#      prefix: /admin/
#      suffix: .jsp
#
logging:
  level:
    com.ziheng.dao: debug

# my register HongRuanFace AppID & SDK
#https://ai.arcsoft.com.cn/ucenter/resource/build/index.html#/login
face:
  appId: DcZzHBJpo9J2cNEQVkFA9z2uY3RzuvsdBGYxAv4L5ws8
  sdkKey: 22QPudYbEChVZfEfVuXLsnYwPW721se1DWCAGo1J999Z
  dllPath: D:\07_projectSpace\GraduationProject\libs\WIN64